set(INCLUDE_FILES
        Include/StarDust/Window.h
        Include/StarDust/Buffer/VertexBuffer.h
        Include/StarDust/Buffer/IndexBuffer.h
        Include/StarDust/VertexArray.h
        Include/StarDust/Utilities/Utils.h
        Include/StarDust/Buffer/VertexBufferLayout.h
        Include/StarDust/Texture.h
        Include/StarDust/Buffer/FrameBuffer.h
        Include/StarDust/Renderer.h
        Include/StarDust/Shader/ShaderProgramRegistry.h
        Include/StarDust/Shader/ShaderProgram.h
        Include/StarDust/Sprite/SpriteAsset.h
        Include/StarDust/Sprite/SpriteAssetRegistry.h
        Include/StarDust/Sprite/SpriteInstance.h
        Include/StarDust/Model/MeshRegistry.h
        Include/StarDust/Model/Mesh.h
        Include/StarDust/Model/Model.h
        Include/StarDust/Model/ModelInstance3D.h
        Include/StarDust/Buffer/RenderBuffer.h
        Include/StarDust/LightSource.h
        Include/StarDust/Model/ModelInstanceSystem.h
        Include/StarDust/Utilities/Math.h
        tools/config.h
)